export enum DELIVERY_TYPE_ENUM {
  MERCADO_LIBRE = 'MELI',
  ANDREANI = 'ANDREANI',
  CORREO_ARGENTINO = 'CORREO_ARGENTINO',
}

export type DELIVERY_TYPE_TYPE =
  | DELIVERY_TYPE_ENUM.MERCADO_LIBRE
  | DELIVERY_TYPE_ENUM.ANDREANI
  | DELIVERY_TYPE_ENUM.CORREO_ARGENTINO;
